#Requires -Version 5.1
<#
.SYNOPSIS
    Pre-uninstall cleanup for coding-agents-kit on Windows.

.DESCRIPTION
    Called by the MSI custom action before files are removed.
    Stops the service, removes the Claude Code hook, and removes
    the auto-start Registry key.
#>
param(
    [string]$Prefix = (Join-Path $env:LOCALAPPDATA 'coding-agents-kit')
)

$ErrorActionPreference = 'SilentlyContinue'

# Trim trailing "\" and "." the MSI CA appends as an escape-safety sentinel
# (see installers/windows/Package.wxs).
$Prefix = $Prefix.TrimEnd([char[]]@('\', '.'))

# Stop the supervisor gracefully (it routes through supervisor.sock and
# runs the full cleanup chain: graceful Falco stop, drain pipes, hook
# remove, close logs). Force-kill any leftover falco.exe only as a fallback
# for legacy installs without the supervisor or for a broken state.
$ctlExe = Join-Path $Prefix 'bin\coding-agents-kit-ctl.exe'
if (Test-Path $ctlExe) {
    Write-Host "Stopping service..."
    & $ctlExe stop 2>$null | Out-Null
}

# Path-scoped fallback kill: only target falco.exe instances launched from
# THIS install's bin\. Without the path filter, an unrelated Falco from
# another project (dev build, separate install, …) could be terminated by
# our uninstall. Mirrors the path-scoped detection used by ctl and
# postinstall.ps1.
$installedFalco = Join-Path $Prefix 'bin\falco.exe'
$falcoProcs = @(Get-Process -Name falco -ErrorAction SilentlyContinue | ForEach-Object {
    try {
        if ($_.Path -and ($_.Path -eq $installedFalco)) { $_ }
    } catch {
        # Access denied (other-user-owned process): not ours, skip.
    }
})
if ($falcoProcs) {
    Write-Host "Force-stopping leftover Falco..."
    $falcoProcs | Stop-Process -Force
    Start-Sleep -Seconds 1
}

# Fallback hook removal — the supervisor already removed it as part of
# `ctl stop`, but call this in case the supervisor didn't run (e.g.,
# legacy install).
if (Test-Path $ctlExe) {
    & $ctlExe hook remove 2>$null | Out-Null
}

# Remove auto-start Registry key
$regPath = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
Remove-ItemProperty -Path $regPath -Name 'CodingAgentsKit' -ErrorAction SilentlyContinue

# Remove bin/ from user PATH
$BinDir = Join-Path $Prefix 'bin'
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if ($userPath -and $userPath -like "*$BinDir*") {
    $newPath = ($userPath -split ';' | Where-Object { $_ -ne $BinDir }) -join ';'
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    Write-Host "Removed $BinDir from user PATH"
}

# Drop dirs the MSI does not own (created at runtime / regenerated by postinstall).
foreach ($dir in @('config', 'run', 'log')) {
    $target = Join-Path $Prefix $dir
    if (Test-Path -LiteralPath $target) {
        Remove-Item -LiteralPath $target -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Write-Host "Uninstall cleanup complete"
